import { UserAuthProvider } from "@/providers/authprovider";
import { BankAccountProvider } from "@/providers/bankaccount";
import { CategoryProvider } from "@/providers/category";
import { StatementProvider } from "@/providers/statement";
import { TransactionProvider } from "@/providers/transactions";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserAuthProvider>
      <BankAccountProvider>
        <CategoryProvider>
          <TransactionProvider>
            <StatementProvider>
              <html lang="en">
                <body className={inter.className}>{children}</body>
              </html>
            </StatementProvider>
          </TransactionProvider>
        </CategoryProvider>
      </BankAccountProvider>
    </UserAuthProvider>
  );
}
