import { BankAccountProvider } from "@/providers/bankaccount";
import { CategoryProvider } from "@/providers/category";
import { TransactionProvider } from "@/providers/transactions";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BankAccountProvider>
      <CategoryProvider>
        <TransactionProvider>
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
        </TransactionProvider>
      </CategoryProvider>
    </BankAccountProvider>
  );
}
